class Domain
  def self.all
    {
      0  => "dziedzina nie ustawiona",
      1  => "najwyższe w hierarchii",
      2  => "czynności (nazwy)",
      3  => "wytwory ludzkie(nazwy)",
      4  => "cechy ludzi i zwierząt",
      5  => "części ciała",
      6  => "związane z myśleniem",
      7  => "związane z porozumiewaniem się",
      8  => "zdarzenia",
      9  => "uczucia, odczucia i emocje",
      10 => "jedzenie",
      11 => "grupy ludzi i rzeczy",
      12 => "miejsca i umiejscowienie",
      13 => "cel działania",
      14 => "obiekty naturalne",
      15 => "ludzie",
      16 => "zjawiska naturalne",
      17 => "nazwy roślin",
      18 => "posiadanie i jego zmiana",
      19 => "procesy naturalne",
      20 => "ilość, liczebność, jednoski miary",
      21 => "zwierzęta",
      22 => "kształty",
      23 => "sytuacje statyczne (stany)",
      24 => "substancje",
      25 => "czas i stosunki czasowe",
      26 => "związek miedzy ludźmi, rzeczami lub ideami",
      27 => "pielęgnacja ciała",
      28 => "zmiana wielkości, temeraturym natężenia, itp.",
      29 => "czasowniki myślenia (szeroko rozumianego)",
      30 => "czasowniki mówienia, śpiewania itp.",
      31 => "czasowniki rywalizacji fizycznej",
      32 => "czasowniki jedzenia",
      33 => "czasowniki oznacz. kontakt fizyczny (dotykanie, uderzenie, rycie itp.)",
      34 => "czasowniki oznacz. wytwarzanie czegoś",
      35 => "czasowniki wyrażające uczucia",
      36 => "czasowniki ruchu",
      37 => "Czasowniki postrzegania (percepcji)",
      38 => "czasowniki posiadania i zmiany posiadania",
      39 => "czasowniki oznacz. wydarzenie i działania społeczne i polityczne",
      40 => "czasowniki stanowe",
      41 => "czasowniki oznacz. zjawiska pogodowe",
      42 => "przymiotniki jakościowe",
      43 => "przymiotniki relacyjne (rzeczownikowe)",
      44 => "przymiotniki odczasownikowe",
      45 => "przymiotniki odprzymiotnikowe (natężenie cechy)",
      46 => "systematyka, klasyfikacja",
      47 => "PWN: all adjective clusters",
      48 => "PWN: all adverbs "
    }
  end
end
